apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: reactjs-sample-pod
          servicePort: 80
      - path: /server
        pathType: Prefix
        backend:
          serviceName: node-server-sample
          servicePort: 80