apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sample.app.com
    http:
      paths:
      - path: /
        frontend:
          serviceName: reactjs-sample-pod
          servicePort: 80
      - path: /backend
        backend:
           serviceName: node-server-sample
          servicePort: 80