export const GET_USERS_EPIC = 'GET_USERS_EPIC';
export const GET_USERS_SUCCEEDED = 'GET_USERS_SUCCEEDED';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';
export const GET_USERS_CANCEL = 'GET_USERS_CANCEL';
export const GET_USERS_READING = 'GET_USERS_READING';
