apiVersion: v1
kind: Service
metadata:
  name: node-server-service
  labels:
    name: node-server-service
    app: node-server-sample
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: node-server-sample-pod
    app: node-server-sample